---

#- name: Update and upgrade apt packages
#  become: true
#  apt:
#    upgrade: yes
#    update_cache: yes

- name: Grab ip link status
  command: ip link
  register: ip_link
  changed_when: False


- name: Install WireGuard
  become: yes
  apt:
    name: wireguard

- name: Install Iptables
  become: yes
  apt:
    name: iptables

- name: Keys generation
  become: yes
  ansible.builtin.shell: wg genkey | tee server.key | wg pubkey > server.pub
  args:
    chdir: /etc/wireguard/
    creates: /etc/wireguard/server.pub

- name: Setup configuration file
  become: yes
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf

- name: Setup private key
  become: yes
  ansible.builtin.shell: echo "PrivateKey = $(cat server.key)" >> /etc/wireguard/wg0.conf
  args:
    chdir: /etc/wireguard/

- name: Create wg0 interface
  become: yes
  command: wg-quick up wg0
  when:
    - '"wg0" not in ip_link.stdout'

#- name: Assign ip address to wg0
#  become: yes
#  command: ip address add 10.0.0.1 dev wg0
#  when:
#    - '"wg0" not in ip_link.stdout'
#
#- name: Up wg0 interface
#  become: yes
#  command: ip link set dev wg0 up
#  when:
#    - '"wg0" not in ip_link.stdout'
